MVCOnlineTicariOtomasyon/Controllers/QRController.cs
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class QRController : Controller
    {
        // GET: QR
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string kod)
        {
            using (MemoryStream ms=new MemoryStream())
            {
                QRCodeGenerator kodüret=new QRCodeGenerator();
                QRCodeGenerator.QRCode karekod = kodüret.CreateQrCode(kod, QRCodeGenerator.ECCLevel.Q);
                using (Bitmap resim = karekod.GetGraphic(10))
                {
                    resim.Save(ms, ImageFormat.Png);
                    ViewBag.karekodimage = "data:image/image;base64," + Convert.ToBase64String(ms.ToArray());
                }
            }
                return View();
        }
    }
}

MVCOnlineTicariOtomasyon/Views/QR/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<div>
    @using (Html.BeginForm("Index", "QR", FormMethod.Post))
    {
        <input type="text" name="kod" />
        <input type="submit" name="QR Oluştur" />
    }
    <br />
    @if (ViewBag.karekodimage!=null)
            {
                <img src="@ViewBag.karekodimage" alt="" style="width:500px; height:500px" />
            }
</div>