MVCOnlineTicariOtomasyon/Controllers/FaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCOnlineTicariOtomasyon.Models.SINIFLAR;
namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class FaturaController : Controller
    {
        // GET: Fatura
        Context c = new Context();
        public ActionResult Index()
        {
            var liste=c.Faturalars.ToList();
            return View(liste);
        }
        [HttpGet]
        public ActionResult FaturaEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FaturaEkle(Faturalar ftr)
        {
           c.Faturalars.Add(ftr);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaGetir(int id)
        {
            var fatura = c.Faturalars.Find(id);
            return View("FaturaGetir",fatura);    
        }
        public ActionResult FaturaGüncelle(Faturalar ftr)
        {
            var fatura=c.Faturalars.Find(ftr.FaturaID);
            fatura.FaturaSeriNo = ftr.FaturaSeriNo;
            fatura.FaturaSıraNo = ftr.FaturaSıraNo;
            fatura.Saat=ftr.Saat;
            fatura.Tarih=ftr.Tarih;
            fatura.TeslimAlan=ftr.TeslimAlan;
            fatura.TeslimEden=ftr.TeslimEden;
            fatura.VergiDairesi=ftr.VergiDairesi;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaDetay(int id)
        {
            var degerler=c.FaturaKalems.Where(x=>x.FaturaaID==id).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniKalem()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniKalem(FaturaKalem fk)
        {
            c.FaturaKalems.Add(fk);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVCOnlineTicariOtomasyon/Views/Fatura/FaturaDetay.cshtml
@using MVCOnlineTicariOtomasyon.Models.SINIFLAR
@model List<FaturaKalem>
@{
    ViewBag.Title = "FaturaDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<br />
<h2>Fatua Detay Sayfası</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active"></li>
</ol>

<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>AÇIKLAMA</th>
        <th>MİKTAR</th>
        <th>BİRİM FİYAT</th>
        <th>TUTAR</th>
    </tr>
    @foreach (var x in Model)
    {


        <tr>
            <td>@x.FaturaaID</td>
            <td>@x.Açıklama</td>
            <td>@x.Miktar</td>
            <td>@x.BirimFiyat</td>
            <td>@x.Tutar</td>
            
        </tr>
    }
</table>
<a href="/Fatura/YeniKalem/" class="btn btn-default"style="background-color:darksalmon">YENİ KALEM GİRİŞİ</a>

MVCOnlineTicariOtomasyon/Views/Fatura/FaturaEkle.cshtml
@model MVCOnlineTicariOtomasyon.Models.SINIFLAR.Faturalar
@{
    
        ViewBag.Title = "FaturaEkle";
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }

    <br />
    <h2>Yeni Fatura Sayfası</h2>
    <br />
    <form class="form-group" method="post">
        @Html.LabelFor(x => x.FaturaSeriNo)
        @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.FaturaSıraNo)
        @Html.TextBoxFor(x => x.FaturaSıraNo, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.VergiDairesi)
        @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Tarih)
        @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Saat)
        @Html.TextBoxFor(x => x.Saat, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.TeslimEden)
        @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.TeslimAlan)
        @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })
        <br />
        <br />
        <button class="btn btn-primary">KAYDET</button>
    </form>

MVCOnlineTicariOtomasyon/Views/Fatura/FaturaGetir.cshtml
@model MVCOnlineTicariOtomasyon.Models.SINIFLAR.Faturalar

@{
    ViewBag.Title = "FaturaGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2> Fatura Güncelleme</h2>
<br />
@using (Html.BeginForm("FaturaGüncelle", "Fatura", FormMethod.Post))
{
    @Html.HiddenFor(x => x.FaturaID)
    @Html.LabelFor(x => x.FaturaSeriNo)
    @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FaturaSıraNo)
    @Html.TextBoxFor(x => x.FaturaSıraNo, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.VergiDairesi)
    @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tarih)
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Saat)
    @Html.TextBoxFor(x => x.Saat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.TeslimEden)
    @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.TeslimAlan)
    @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">GÜNCELLE</button>
}

MVCOnlineTicariOtomasyon/Views/Fatura/Index.cshtml
@using MVCOnlineTicariOtomasyon.Models.SINIFLAR
@model List<Faturalar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px">
    <tr>

        <th>FATURA SERİ & SIRA  NO</th>


        <th>TARİH</th>
        <th>SAAT</th>


        <th>TOPLAM</th>
        <th>GÜNCELLE</th>
        <th>DETAYLAR</th>
        <th>YENİ KALEM</th>

    </tr>
    @foreach (var f in Model)
    {
        <tr>

            <td>@f.FaturaSeriNo @f.FaturaSıraNo</td>


            <td>@f.Tarih</td>
            <td>@f.Saat</td>

            <td>@f.Toplam ₺</td>
            <td><a href="/Fatura/FaturaGetir/@f.FaturaID" class="btn btn-success">GÜNCELLE</a></td>
            <td><a href="/Fatura/FaturaDetay/@f.FaturaID" class="btn btn-default" style="background-color:darkgoldenrod">DETAYLAR</a></td>
            <td><a href="/Fatura/FaturaDetay/@f.FaturaID" class="btn btn-default" style="background-color:olive">KALEM</a></td>
        </tr>
    }

</table>
<a href="/Fatura/FaturaEkle" class="btn btn-primary">FATURA EKLE</a>
<br />
<br />
<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#Modal1">POPUP PENCERESİ</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Popup Diyalog Ekranı</h2>
            </div>
            <div class="modal-body">
                <table class="table table-bordered">
                    <tr>
                        <td>Seri No</td>
                        <td>Sıra No</td>
                        <td>Tutar</td>
                    </tr>
                    @foreach (var x in Model)
                    {
                        <tr>
                            <td>@x.FaturaSeriNo</td>
                            <td>@x.FaturaSıraNo</td>
                            <td>@x.Toplam</td>
                        </tr>
                    }
                </table>
                <button type="button"class="btn btn-danger" data-dismiss="modal">TAMAM</button>
            </div>
        </div>
    </div>
</div>

MVCOnlineTicariOtomasyon/Views/Fatura/YeniKalem.cshtml
@model MVCOnlineTicariOtomasyon.Models.SINIFLAR.FaturaKalem 
@{
    ViewBag.Title = "YeniKalem";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Kalem Girişi</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.Açıklama)
    @Html.TextBoxFor(x => x.Açıklama, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Miktar)
    @Html.TextBoxFor(x => x.Miktar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.BirimFiyat)
    @Html.TextBoxFor(x => x.BirimFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tutar)
    @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FaturaaID)
    @Html.TextBoxFor(x => x.FaturaaID, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">KAYDET</button>
</form>