MVCOnlineTicariOtomasyon/Controllers/SatışController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCOnlineTicariOtomasyon.Models.SINIFLAR;
namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class SatışController : Controller
    {
        // GET: Satış
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.SatışHaretkets.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniSatış()
        {
            List<SelectListItem> deger1 = (from x in c.Ürüns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.ÜrünAd,
                                               Value = x.ÜrünID.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from x in c.Caris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyAd,
                                               Value = x.CariID.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyAd,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult YeniSatış(SatışHaretket s)
        {
            s.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SatışHaretkets.Add(s);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatışGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Ürüns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.ÜrünAd,
                                               Value = x.ÜrünID.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from x in c.Caris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyAd,
                                               Value = x.CariID.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyAd,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            var deger = c.SatışHaretkets.Find(id);
            return View("SatışGetir", deger);
        }
        public ActionResult SatışGüncelle(SatışHaretket st)
        {
            var deger = c.SatışHaretkets.Find(st.SatışId);
            deger.CariId=st.CariId;
            deger.Adet=st.Adet;
            deger.Fiyat=st.Fiyat;
            deger.PersonelId=st.PersonelId; 
            deger.Tarih=st.Tarih;
            deger.ToplamTutar=st.ToplamTutar;
            deger.ÜrünId=st.ÜrünId;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatışDetay(int id)
        {
            var degerler = c.SatışHaretkets.Where(x=>x.SatışId==id).ToList();
            return View(degerler);
        }
    }
}

MVCOnlineTicariOtomasyon/Views/Satış/Index.cshtml
@using MVCOnlineTicariOtomasyon.Models.SINIFLAR
@model List<SatışHaretket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<table id="tbl1" class="table table-bordered" style="margin-top:20px">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ürün</th>
            <th>Cari</th>
            <th>Personel</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam</th>
            <th>Tarih</th>
            <th>Güncelle</th>
            <th>Detaylar</th>
        </tr>
    </thead>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.SatışId</td>
            <td>@k.Ürün.ÜrünAd</td>
            <td>@k.Cari.CariAd @k.Cari.CariSoyAd</td>
            <td>@k.Personel.PersonelAd @k.Personel.PersonelSoyAd</td>
            <td>@k.Adet</td>
            <td>@k.Fiyat</td>
            <td>@k.ToplamTutar</td>
            <td>@k.Tarih</td>
            <td><a href="/Satış/SatışGetir/@k.SatışId" class="btn btn-success">GÜNCELLE</a></td>
            <td><a href="/Satış/SatışDetay/@k.SatışId" class="btn btn-default" style="background-color:darkgoldenrod">DETAYLAR</a>

        </tr>
    }
</table>
<a href="/Satış/YeniSatış" class="btn btn-primary">Yeni Satış Yap</a>

<link href="~/Content/bootstrap.css" rel="stylesheet" />

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>




<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tbl1').dataTable({});
</script>

MVCOnlineTicariOtomasyon/Views/Satış/SatışDetay.cshtml
@using MVCOnlineTicariOtomasyon.Models.SINIFLAR
@model List<SatışHaretket>
@{
    ViewBag.Title = "SatışDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Satış Detayı</h2>
<br />

<table class="table table-condensed">
    <tr>
        <th>SATIŞ ID</th>
        <th>ÜRÜN</th>
        <th>CARİ</th>
        <th>PERSONEL</th>
        <th>FİYAT</th>
        <th>ADET</th>
        <th>TOPLAM</th>
        <th>TARİH</th>
        
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.SatışId</td>
            <td>@x.Ürün.ÜrünAd</td>
            <td>@x.Cari.CariAd  @x.Cari.CariSoyAd</td>
            <td>@x.Personel.PersonelAd  @x.Personel.PersonelSoyAd</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            
        </tr>
    }
</table>
<button class="btn btn-default" style="background-color:darkkhaki">YAZDIR</button>

MVCOnlineTicariOtomasyon/Views/Satış/SatışGetir.cshtml
@model MVCOnlineTicariOtomasyon.Models.SINIFLAR.SatışHaretket
@{
    ViewBag.Title = "SatışGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Satış Güncelleme</h2>
<br />
@using (Html.BeginForm("SatışGüncelle", "Satış", FormMethod.Post))
{
    @Html.HiddenFor(x => x.SatışId)

    @Html.LabelFor(x => x.Ürün)
    @Html.DropDownListFor(x => x.ÜrünId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.CariId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.DropDownListFor(x => x.PersonelId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet)
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ToplamTutar)
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tarih)
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">GÜNCELLE</button>
}

MVCOnlineTicariOtomasyon/Views/Satış/YeniSatış.cshtml
@model MVCOnlineTicariOtomasyon.Models.SINIFLAR.SatışHaretket
@{
    ViewBag.Title = "YeniSatış";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2> Yeni Satış Sayfası</h2>
<form class="form-group" method="post">
    @Html.LabelFor(x => x.Ürün)
    @Html.DropDownListFor(x => x.ÜrünId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.CariId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.DropDownListFor(x => x.PersonelId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet)
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ToplamTutar)
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">SATIŞ YAP</button>
</form>