MVCOnlineTicariOtomasyon/Models/SINIFLAR/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCOnlineTicariOtomasyon.Models.SINIFLAR
{
    public class Personel
    {
        [Key]
        public int PersonelID {  get; set; }

        [Display(Name ="Personel Adı")]
        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string PersonelAd {  get; set; }


        [Display(Name = "Personel Soyadı")]
        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string PersonelSoyAd{  get; set; }


        [Display(Name = "Personel Görsel")]
        [Column(TypeName = "Varchar")]
        [StringLength(350)]
        public string PersonelGörsel{  get; set; }
        public ICollection<SatışHaretket> SatışHaretkets { get; set; }
        public int DepartmanId {  get; set; }
        public virtual Departman Departman { get; set; }    

    }
}

MVCOnlineTicariOtomasyon/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCOnlineTicariOtomasyon.Models.SINIFLAR;

namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        Context c=new Context();
        public ActionResult Index()
        {
            var degerler=c.Personels.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult PersonelEkle()
        {

            List<SelectListItem> deger1 = (from x in c.Departmen.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAD,
                                               Value = x.DepartmanID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }
        [HttpPost]
        public ActionResult PersonelEkle(Personel p)
        {
            if (Request.Files.Count > 0)
            {
                string doysaadi=Path.GetFileName(Request.Files[0].FileName);
                string uzanti=Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Image/" + doysaadi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                p.PersonelGörsel="/Image/" + doysaadi + uzanti; 
            }
            c.Personels.Add(p);
            c.SaveChanges();
            return View("Index");
        }
        public ActionResult PersonelGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Departmen.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAD,
                                               Value = x.DepartmanID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            var prs = c.Personels.Find(id);
            return View("PersonelGetir",prs);
        }
        public ActionResult PersonelGüncelle(Personel p)
        {
            var prsn = c.Personels.Find(p.PersonelID);
            prsn.PersonelAd=p.PersonelAd;
            prsn.PersonelSoyAd=p.PersonelSoyAd;
            prsn.PersonelGörsel = p.PersonelGörsel;
            prsn.DepartmanId=prsn.PersonelID;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelListe()
        {
            var deger = c.Personels.ToList();
            return View(deger);
        }
    }
}

MVCOnlineTicariOtomasyon/Views/Personel/Index.cshtml
@using MVCOnlineTicariOtomasyon.Models.SINIFLAR
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered"style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>PERSONEL AD</th>
        <th>SOYAD</th>
        <th>DEPARTMAN</th>
      
        <th>GÜNCELLE</th>
        <th>SATIŞLAR</th>
    </tr>
    @foreach(var k in Model)
            {
                <tr>
                    <td>@k.PersonelID</td>
                    <td>@k.PersonelAd</td>
                    <td>@k.PersonelSoyAd</td>
                    <td>@k.Departman.DepartmanAD</td>
                   
                
                    <td><a href="/Personel/PersonelGetir/@k.PersonelID" class="btn btn-success">GÜNCELLE</a></td>
                    <td><a href="/Departman/DepartmanPersonelSatış/@k.PersonelID" class="btn btn-default" style="background-color:darkgoldenrod">DETAYLAR</a></td>
                </tr>
            }
</table>
<a href="/Personel/PersonelEkle" class="btn btn-info">PERSONEL EKLE</a>

MVCOnlineTicariOtomasyon/Views/Personel/PersonelEkle.cshtml
@model MVCOnlineTicariOtomasyon.Models.SINIFLAR.Personel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Personel Sayfası</h2>
<br />
@using (Html.BeginForm("PersonelEkle", "Personel", FormMethod.Post, new { enctype = "mıltipart/form-data" }))
{

    <form class="form-group"method="post">
    @Html.LabelFor(x => x.PersonelAd)
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelSoyAd)
    @Html.TextBoxFor(x => x.PersonelSoyAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelGörsel)
    @*@Html.TextBoxFor(x => x.PersonelGörsel, new { @class = "form-control" })*@
    <input type="file"name="PersonelGörsel" />
    <br />
    @Html.LabelFor(x => x.Departman)
    @Html.DropDownListFor(x => x.DepartmanId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">KAYDET</button>
</form>
}

MVCOnlineTicariOtomasyon/Views/Personel/PersonelGetir.cshtml
@model MVCOnlineTicariOtomasyon.Models.SINIFLAR.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Personel Güncelleme Sayfası</h2>
<br />
@using (Html.BeginForm("PersonelGüncelle", "Personel", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.PersonelID)
        @Html.LabelFor(x => x.PersonelAd)
        @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelSoyAd)
        @Html.TextBoxFor(x => x.PersonelSoyAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.PersonelGörsel)
        @Html.TextBoxFor(x => x.PersonelGörsel, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Departman)
        @Html.DropDownListFor(x=> x.DepartmanId, (List<SelectListItem>)ViewBag.dgr1, new {@class="form-control"})
        <br />
        <button class="btn btn-warning">GÜNCELLE</button>
    </div>
}

MVCOnlineTicariOtomasyon/Views/Personel/PersonelListe.cshtml
@using MVCOnlineTicariOtomasyon.Models.SINIFLAR
@model List<Personel>
@{
    ViewBag.Title = "PersonelListe";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Contacts</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4//dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>PERSONELLER</h1>
                    </div>

                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="card card-solid">
                <div class="card-body pb-0">
                    <div class="row d-flex align-items-stretch">
                        @foreach (var x in Model)
                        {


                            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                                <div class="card bg-light">
                                    <div class="card-header text-muted border-bottom-0">
                                        @x.Departman.DepartmanAD
                                    </div>
                                    <div class="card-body pt-0">

                                        <div class="row">
                                            <div class="col-7">
                                                <h2 class="lead"><b>@x.PersonelAd @x.PersonelSoyAd</b></h2>
                                                <p class="text-muted text-sm"><b>About: </b> Web Designer / UX / Graphic Artist / Coffee Lover </p>
                                                <ul class="ml-4 mb-0 fa-ul text-muted">
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: Demo Street 123, Demo City 04312, NJ</li>
                                                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                                </ul>
                                            </div>
                                            <div class="col-5 text-center">
                                                <img src="@x.PersonelGörsel"alt="" class="img-circle img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="text-right">
                                            <a href="/Personel/PersonelGetir/@x.PersonelID" class="btn btn-sm bg-teal">
                                                <i class="fas fa-comments"></i>
                                            </a>
                                            <a href="/Departman/DepartmanPersonelSatış/@x.PersonelID" class="btn btn-sm btn-primary">
                                                <i class="fas fa-user"></i> Satış Geçmişi
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }

                    </div>

                </div>
                <!-- /.card-body -->
                <!-- /.card-footer -->
            </div>
            <!-- /.card -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
</body>
</html>